# Generated by Django 3.2 on 2021-04-27 17:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='cake',
            fields=[
                ('cakeid', models.AutoField(primary_key=True, serialize=False)),
                ('createdate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description', models.CharField(max_length=255)),
                ('eggless', models.BooleanField(default=True)),
                ('flavour', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('ingredients', models.CharField(max_length=255)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('ratings', models.IntegerField(blank=True, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='allcake.imagemodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
