# Generated by Django 3.2 on 2021-04-29 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cakeid', models.IntegerField()),
                ('orderdate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('image', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('weight', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('ordered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('orderdate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('address', models.CharField(max_length=255)),
                ('pincode', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('price', models.IntegerField()),
                ('pending', models.BooleanField(default=True)),
                ('completed', models.BooleanField(default=False)),
                ('mode', models.CharField(default='Cash', max_length=20)),
                ('cakes', models.ManyToManyField(to='allcake.cart')),
            ],
        ),
    ]
